### ISSUE TITLE
Share install failure on Fedora 29

### ISSUE THREAD

**Issue by Grinnz** [Perl5-Alien/Alien-m4#3]
When forcing a share install, Alien::m4 fails to build on Fedora 29, kernel version 5.0.16-200.fc29.x86_64. Build log: https://paste.fedoraproject.org/paste/CbPOCU96aLrO8CKSsgur0w/raw
```
freadahead.c: In function 'freadahead':
freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
```
Centos 7 does not exhibit the same issue.

**Comment by plicease** [comment]
This is fixed in #5.  Looks like the problem is recent glibc is incompatible with the latest version of m4 which is a couple of years old.  The patch that Debian uses seems to also work for Fedora 29 also.

**Comment by plicease** [comment]
fixed in `0.18` on its way to CPAN now.
